# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('price_factor', models.SmallIntegerField(default=0, verbose_name='Increase or decrease the base price by the following percentage.  Use negative values to decrease price.')),
                ('grinds', models.ManyToManyField(to='product_options.CoffeeGrind')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_options.CoffeeRoast')),
                ('sizes', models.ManyToManyField(to='product_options.CoffeeVolume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=64)),
                ('discount', models.PositiveSmallIntegerField(default=15, help_text='Positive, whole numbers only', verbose_name='Percent discount')),
                ('expiration_date', models.DateTimeField(verbose_name='Date and time that promotion ends')),
                ('coffees', models.ManyToManyField(to='products.Coffee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
