# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='expiration_date',
            field=models.DateTimeField(help_text='Server timezone is UTC (Coordinated Universal Time)', verbose_name='Date and time that promotion ends'),
        ),
    ]
