# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0002_shirtsize'),
        ('products', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sizes', models.ManyToManyField(to='product_options.ShirtSize', verbose_name='Shirt Sizes available (if applicable)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VarietyPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('coffee_qty', models.PositiveSmallIntegerField(default=0, verbose_name='Number of bags of coffee in pack (if applicable)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coffees', models.ManyToManyField(to='products.Coffee', verbose_name='Coffees available in pack (if applicable)')),
                ('merchandise', models.ManyToManyField(to='products.Merchandise', verbose_name='Other merchandise available in pack (if applicable)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
