# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0002_auto_20161107_2200'),
        ('products', '0003_auto_20161107_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSaleCoffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('size', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('price_per_pound', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.URLField()),
                ('grinds', models.ManyToManyField(to='product_options.CoffeeGrind')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_options.CoffeeRoast')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
