# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161024_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'verbose_name_plural': 'Merchandise'},
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='coffees',
            field=models.ManyToManyField(blank=True, to='products.Coffee'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='product_options.ShirtSize', verbose_name='Shirt Sizes available (if applicable)'),
        ),
        migrations.AlterField(
            model_name='varietypack',
            name='coffees',
            field=models.ManyToManyField(blank=True, to='products.Coffee', verbose_name='Coffees available in pack (if applicable)'),
        ),
        migrations.AlterField(
            model_name='varietypack',
            name='merchandise',
            field=models.ManyToManyField(blank=True, to='products.Merchandise', verbose_name='Other merchandise available in pack (if applicable)'),
        ),
    ]
