# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161107_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(help_text='Server timezone is UTC (Coordinated Universal Time)', verbose_name='Date and time that coupon stops working'),
        ),
    ]
