# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_wholesalecoffee_size'),
        ('products', '0004_auto_20161110_2048'),
    ]

    operations = [
    ]
