# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_subscription_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Number of weeks between each shipment'),
        ),
    ]
