# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20161114_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.PositiveSmallIntegerField(verbose_name='Number of weeks between each shipment'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('frequency', 'price', 'stripe_id')]),
        ),
    ]
