# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0002_auto_20161107_2200'),
        ('products', '0013_auto_20161116_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholesalecoffee',
            options={'verbose_name': 'Coffee - Wholesale', 'verbose_name_plural': 'Coffees - Wholesale'},
        ),
        migrations.RemoveField(
            model_name='wholesalecoffee',
            name='price_per_pound',
        ),
        migrations.AddField(
            model_name='wholesalecoffee',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductPromotion', verbose_name='To feature this product, select a promotional deal.'),
        ),
        migrations.AddField(
            model_name='wholesalecoffee',
            name='price_factor',
            field=models.SmallIntegerField(default=0, verbose_name='Increase or decrease the base price by the following percentage.  Use negative values to decrease price.'),
        ),
        migrations.AddField(
            model_name='wholesalecoffee',
            name='sizes',
            field=models.ManyToManyField(to='product_options.CoffeeVolume'),
        ),
    ]
