# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20161116_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='ship_wt',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4, verbose_name='Shipping Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietypack',
            name='ship_wt',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4, verbose_name='Shipping Weight'),
            preserve_default=False,
        ),
    ]
