# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20161117_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='wholesale',
            field=models.BooleanField(default=False, help_text='Check this if coffee is only sold in wholesale volumes.'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='display',
            field=models.BooleanField(default=True, help_text='If this is unchecked, products under this promotion will not be displayed in the featured products section.', verbose_name='Display in Featured Section?'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Number of weeks between each shipment'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='varietypack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='varietypack',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wholesalecoffee',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_id',
        ),
    ]
