# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20161118_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecoffee',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='wholesalecoffee',
            name='grinds',
        ),
        migrations.RemoveField(
            model_name='wholesalecoffee',
            name='roast',
        ),
        migrations.RemoveField(
            model_name='wholesalecoffee',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='wholesale_coffees',
        ),
        migrations.DeleteModel(
            name='WholeSaleCoffee',
        ),
    ]
