# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='charge_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='coffee',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='merch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='subscriptions',
            field=models.TextField(blank=True),
        ),
    ]
