# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20161107_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='totalItems',
            field=models.PositiveSmallIntegerField(verbose_name='Total Items'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='totalPrice',
            field=models.FloatField(verbose_name='Total Price'),
        ),
    ]
