# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161107_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='other_info',
            field=models.TextField(blank=True),
        ),
    ]
