# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customerorder_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
