# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shippingfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='shipping_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='subTotalPrice',
            field=models.FloatField(default=0, verbose_name='Price before coupons and shipping'),
        ),
    ]
