# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Bob', max_length=64),
            preserve_default=False,
        ),
    ]
