# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 2, 17, 22, 23, 523763, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountrate',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discountrate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 2, 17, 22, 42, 237309, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
