# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20161102_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_rate',
            field=models.ForeignKey(blank=True, help_text='Leave blank for no discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.DiscountRate'),
        ),
    ]
