# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20161102_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
