# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20161103_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
