# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_shippingaddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together=set([('customer', 'name', 'address', 'address2', 'city', 'state', 'zipcode')]),
        ),
    ]
