# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20161112_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(help_text='Price per pound')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='discount_rate',
        ),
        migrations.DeleteModel(
            name='DiscountRate',
        ),
        migrations.AddField(
            model_name='customer',
            name='wholesale_price',
            field=models.ForeignKey(blank=True, help_text='Leave blank for no discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.WholesalePrice'),
        ),
    ]
