# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20161114_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
