# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wholesale_price',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use default price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.WholesalePrice'),
        ),
        migrations.AlterField(
            model_name='wholesaleprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per pound', max_digits=5, unique=True),
        ),
    ]
