# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20161115_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleprice',
            name='price',
        ),
        migrations.AddField(
            model_name='wholesaleprice',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=5, help_text='Specific customers will receive this discount on wholesale volumes.', unique=True, verbose_name='Percent discount'),
            preserve_default=False,
        ),
    ]
