# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20161116_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholesaleprice',
            options={'verbose_name': 'Wholesale Price Discount'},
        ),
    ]
