# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20161119_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.TextField(blank=True),
        ),
    ]
