# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeGrind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='Type of Grind')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Do not include "Roast" in the name', max_length=24, verbose_name='Type of roast (i.e. Medium, Dark, Single Origin)')),
                ('origin', models.CharField(blank=True, help_text='Leave blank if not Single Origin', max_length=24, verbose_name='Country of origin (if Single Origin)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(choices=[('oz', 'Ounces'), ('lbs', 'Pounds')], default='oz', max_length=3, verbose_name='Unit of Measurment')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='Number of units')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Base price (dollars) for any coffee at this weight')),
            ],
            options={
                'ordering': ['-unit', 'qty'],
            },
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('XS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('2XL', '2X-Large'), ('3XL', '3X-Large')], max_length=3, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
