# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0003_auto_20161117_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtsize',
            name='size',
            field=models.CharField(choices=[('0', 'X-Small'), ('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'X-Large'), ('5', '2X-Large'), ('6', '3X-Large')], max_length=3, unique=True),
        ),
    ]
