# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0004_auto_20161117_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirtsize',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='size',
            field=models.CharField(choices=[('XS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('2XL', '2X-Large'), ('3XL', '3X-Large')], max_length=3, unique=True),
        ),
    ]
