# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_options', '0005_auto_20161117_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shirtsize',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coffeevolume',
            name='base_price_plan',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Base price (dollars) for a subscription at this weight'),
            preserve_default=False,
        ),
    ]
