# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('link_title', models.TextField()),
                ('desciprtion', models.TextField()),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
