# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, help_text='Add an optional off-site URL.')),
                ('image_url', models.URLField(help_text='Link the image that you would like at the head of the post from Amazon S3.')),
                ('old_created_at', models.DateField(blank=True, help_text='YYYY-MM-DD. Leave field blank if this is a new post.', null=True, verbose_name='Date of previous publication')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
        ),
    ]
