# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161030_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='desciprtion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='link_title',
            field=models.TextField(),
        ),
    ]
