# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161107_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
