# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161031_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
    ]
