# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161031_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='old_created_at',
            field=models.DateTimeField(blank=True, help_text='Leave field blank if this is a new post.', null=True, verbose_name='Date of previous publication'),
        ),
    ]
