# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=36)),
                ('type', models.CharField(max_length=36)),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('url', models.URLField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
