# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=36)),
                ('address', models.TextField()),
                ('phone_number', models.PositiveIntegerField(help_text='Format must be Area Code + Phone Number (Numbers only)')),
                ('url', models.URLField()),
                ('lng', models.FloatField(blank=True, help_text='Leave this field blank.  Data will be aquired automatically from Google Maps', null=True, verbose_name='Longitude')),
                ('lat', models.FloatField(blank=True, help_text='Leave this field blank.  Data will be aquired automatically from Google Maps', null=True, verbose_name='Latitude')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=36, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(help_text='Choose the type of store associated with the location.', on_delete=django.db.models.deletion.CASCADE, to='locations.StoreType'),
        ),
    ]
