# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='phone_number',
            new_name='number',
        ),
    ]
