# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.IntegerField(default='', help_text='Format should be Area Code + Phone Number'),
        ),
    ]
