# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161031_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='number',
            new_name='phone_number',
        ),
    ]
