# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161031_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, help_text='Leave this field blank.  Data will be aquired automatically from Google Maps', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, help_text='Leave this field blank.  Data will be aquired automatically from Google Maps', null=True, verbose_name='Longitude'),
        ),
    ]
