# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_storetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.StoreType'),
        ),
    ]
