# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20161031_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.PositiveIntegerField(help_text='Numbers only'),
        ),
    ]
