# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_hours',
            name='saturday_close',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='saturday_open',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='sunday_close',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='sunday_open',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
