# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafe_content_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe_hours',
            options={'verbose_name_plural': 'Cafe Hours'},
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='friday_close',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='friday_open',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='monday_close',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='monday_open',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='saturday_close',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='saturday_open',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='sunday_close',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='sunday_open',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='thursday_close',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='thursday_open',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='tuesday_close',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='tuesday_open',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='wednesday_close',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cafe_hours',
            name='wednesday_open',
            field=models.CharField(max_length=12),
        ),
    ]
