# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20161130_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_hours',
            name='friday_close',
            field=models.CharField(max_length=12),
        ),
    ]
