# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullWidthSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('header', models.CharField(max_length=32)),
                ('first_paragraph', models.TextField()),
                ('second_paragraph', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMemberEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=24)),
                ('member_story', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
