# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullwidthsection',
            name='image_url',
            field=models.URLField(help_text='Link the image that you would like displayed in a large section from Amazon S3.'),
        ),
        migrations.AlterField(
            model_name='fullwidthsection',
            name='second_paragraph',
            field=models.TextField(blank=True, help_text='Use this field if you would like a break(space) between text.'),
        ),
        migrations.AlterField(
            model_name='staffmemberentry',
            name='member_story',
            field=models.TextField(help_text='A short description of the employee.'),
        ),
    ]
