# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(max_length=36)),
                ('description', models.TextField(default='Description for Happy Cup Coffee Cafe in Town Hall!')),
                ('address', models.CharField(max_length=36)),
                ('phone_number', models.CharField(max_length=14)),
                ('link_text', models.CharField(max_length=120)),
                ('link_url', models.URLField(help_text='Link the document URL from Amazon S3 here.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cafe_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_open', models.CharField(max_length=12)),
                ('monday_close', models.CharField(max_length=12)),
                ('tuesday_open', models.CharField(max_length=12)),
                ('tuesday_close', models.CharField(max_length=12)),
                ('wednesday_open', models.CharField(max_length=12)),
                ('wednesday_close', models.CharField(max_length=12)),
                ('thursday_open', models.CharField(max_length=12)),
                ('thursday_close', models.CharField(max_length=12)),
                ('friday_open', models.CharField(max_length=12)),
                ('friday_close', models.CharField(max_length=12)),
                ('saturday_open', models.CharField(blank=True, max_length=12, null=True)),
                ('saturday_close', models.CharField(blank=True, max_length=12, null=True)),
                ('sunday_open', models.CharField(blank=True, max_length=12, null=True)),
                ('sunday_close', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cafe Hours',
            },
        ),
        migrations.CreateModel(
            name='CafeCarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='Link the image that you would like displayed in a the carousel from Amazon S3.')),
                ('image_alternate_text', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
