# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, help_text='Link from Amazon S3. To ensure proper styling, image should be no smaller than 945 pixels wide and 532 pixels high.', verbose_name='Image on page top')),
                ('roaster_line1', models.CharField(blank=True, max_length=32, verbose_name='Happy Cup Roaster: Line 1')),
                ('roaster_line2', models.CharField(blank=True, max_length=32, verbose_name='Happy Cup Roaster: Line 2')),
                ('account_line1', models.CharField(blank=True, max_length=32, verbose_name='Account Questions: Line 1')),
                ('account_line2', models.CharField(blank=True, max_length=32, verbose_name='Account Questions: Line 2')),
                ('account_line3', models.CharField(blank=True, max_length=32, verbose_name='Account Questions: Line 3')),
                ('billing_line1', models.CharField(blank=True, max_length=32, verbose_name='Billing Questions: Line 1')),
                ('billing_line2', models.CharField(blank=True, max_length=32, verbose_name='Billing Questions: Line 2')),
                ('billing_line3', models.CharField(blank=True, max_length=32, verbose_name='Billing Questions: Line 3')),
                ('media_kit_url', models.URLField(blank=True, help_text='Link from Amazon S3')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
