# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='hq_address',
            field=models.CharField(default='ttt', max_length=64, verbose_name='Address of company headquarters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='main_phone',
            field=models.CharField(default='ttt', max_length=14, verbose_name="Company's primary phone number"),
            preserve_default=False,
        ),
    ]
