# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161202_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='account_line1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='account_line2',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='account_line3',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='billing_line1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='billing_line2',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='billing_line3',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hq_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='roaster_line1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='roaster_line2',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='account_contact',
            field=models.CharField(blank=True, max_length=32, verbose_name='Contact for Account Questions'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='account_email',
            field=models.EmailField(blank=True, max_length=48, verbose_name='Account Questions Email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='account_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Account Questions Phone'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='billing_contact',
            field=models.CharField(blank=True, max_length=32, verbose_name='Contact For Billing Questions'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=48, verbose_name='Billing Questions Email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Billing Questions Phone'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hq_address_line1',
            field=models.CharField(default='ttt', max_length=32, verbose_name='Street of company headquarters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hq_address_line2',
            field=models.CharField(default='ttt', max_length=32, verbose_name='City, State, Zip of company headquarters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='roaster_address',
            field=models.CharField(blank=True, max_length=32, verbose_name="Happy Cup Roaster's Address"),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='roaster_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name="Happy Cup Roaster's Phone"),
        ),
    ]
